### ISSUE TITLE
SSL verify disable is being ignored

### ISSUE THREAD

**Issue by tony-spencer** [cheald/manticore#52] opened 2016-05-09 15:44 UTC
I don' t know if I've used it incorrectly but in the attached example I'm getting an unexpected exception when I've set the client to never verify SSL:

`Manticore::ClientProtocolException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  block in initialize at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/response.rb:37
                 call at org/jruby/RubyProc.java:318
                 call at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/response.rb:79
            call_once at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/response.rb:256
                 code at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/response.rb:153
                <top> at manticoretest.rb:8`

**JRuby version:** 9.0.5.0
**OS:** Mac El Capitan 10.11.4

[manticoretest.rb.gz](https://github.com/cheald/manticore/files/255320/manticoretest.rb.gz)

**Comment by tony-spencer** [comment] 2016-05-09 16:47
Hmm. Well I did this: `rvm osx-ssl-certs update all`

and now getting:
`Unhandled Java exception: java.security.KeyStoreException: problem accessing trust storejava.io.IOException: Invalid keystore format
java.security.KeyStoreException: problem accessing trust storejava.io.IOException: Invalid keystore format
                       engineInit at sun/security/ssl/TrustManagerFactoryImpl.java:75
                             init at javax/net/ssl/TrustManagerFactory.java:250
                loadTrustMaterial at org/apache/http/conn/ssl/SSLContextBuilder.java:106
                           invoke at java/lang/reflect/Method.java:606
                setup_trust_store at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/client.rb:622
  ssl_socket_factory_from_options at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/client.rb:602
                     pool_builder at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/client.rb:394
                             pool at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/client.rb:402
                       initialize at /Users/tony/.rvm/gems/jruby-9.0.5.0/gems/manticore-0.6.0-java/lib/manticore/client.rb:208
                            <top> at manticoretest.rb:5
              invokeWithArguments at java/lang/invoke/MethodHandle.java:566`

**Comment by tony-spencer** [comment] 2016-05-11 15:35
Ok I can run the script with no issues on Ubuntu some it's something wonky with Mac. Seems like Manticore is still performing some SSL activity on Mac despite verify: disable

**Comment by andrewvc** [comment] 2016-08-05 17:13
@tony-spencer see #53

**Comment by cheald** [comment] 2018-05-28 01:20
I'm looking at this (and #53) but I can't seem to reproduce this in my Ubuntu environment. Expired SSL certs, broken SSL certs - they all work without incident when `verify: :none` is passed.

I'd like to fix it, but I need a failing test to be able to pin it down.

**Comment by F-PMOR** [comment] 2020-05-29 14:55
Hi @cheald , do you still need an exemple where it doesn't work ?

**Comment by cheald** [comment] 2020-05-30 02:12
Yes, a reproducible test case, or even better, a failing unit test would be very useful.

**Comment by kares** [comment] 2022-01-18 09:11
seems to be the same underlying cause as in https://github.com/cheald/manticore/issues/53, resolved in MC (>=) 0.8.0

**Closed by kares** 2022-01-18 09:11 UTC
